-- AUTO-GENERATED FILE. DO NOT EDIT BY HAND.
-- Generated by scripts/generate-schema-snapshot.ts
-- Regenerate with: npx ts-node scripts/generate-schema-snapshot.ts
--
-- Frozen schema snapshot for migrations 001-027
-- (src/sql/schema.sql + src/main/migrations/001.js..027.js).
--
-- Bootstraps a fresh database (web, and eventually new desktop installs) to
-- the exact schema state produced by running schema.sql followed by
-- migrations 001-027 through the historical (better-sqlite3-sync)
-- MigrationRunner. Includes the `migrations` bookkeeping table, pre-seeded
-- with rows for 001-027, so that if the desktop MigrationRunner ever opens
-- a database bootstrapped from this snapshot, it treats 001-027 as already
-- applied and does not attempt to re-run them.
--
-- Future schema changes belong in src/core/db/migrations (028+), written
-- platform-free against DatabaseDriver -- NOT in this file and NOT as new
-- files under src/main/migrations.

CREATE TABLE "account" (
              "id" INTEGER PRIMARY KEY AUTOINCREMENT,
              "chartId" INTEGER NOT NULL,
              "date" DATETIME,
              "name" STRING NOT NULL,
              "code" VARCHAR(40),
              "createdAt"	DATETIME, -- order matters, 4 new columns must be added after the existing columns
              "updatedAt"	DATETIME,
              "address" TEXT,
              "phone1" VARCHAR(20),
              "phone2" VARCHAR(20),
              "goodsName" TEXT, "isActive" BOOLEAN NOT NULL DEFAULT 1, "discountProfileId" INTEGER REFERENCES "discount_profiles"("id"), "uuid" TEXT,

              FOREIGN KEY("chartId") REFERENCES "chart"("id")
            );

CREATE TABLE "attribute_definitions" ( -- "020 migration"
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL UNIQUE,
    "label" TEXT NOT NULL,
    "unit" TEXT,
    "valueType" TEXT NOT NULL DEFAULT 'text',
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "isActive" BOOLEAN NOT NULL DEFAULT 1,
    "isPublic" BOOLEAN NOT NULL DEFAULT 0, -- "021 migration"
    "createdAt" DATETIME,
    "updatedAt" DATETIME
, "uuid" TEXT);

CREATE TABLE "chart" (
              id INTEGER PRIMARY KEY AUTOINCREMENT,
              date DATETIME,
              name STRING NOT NULL,
              userId INTEGER,
              code INTEGER,
              type STRING NOT NULL CHECK (type IN ('Asset', 'Liability', 'Equity', 'Revenue', 'Expense')),
              createdAt DATETIME,
              updatedAt DATETIME, "parentId" INTEGER REFERENCES "chart"("id"), "uuid" TEXT,
              FOREIGN KEY(userId) REFERENCES users(id) ON DELETE NO ACTION
            );

CREATE TABLE "discount_profiles" ( -- "015 migration"
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT NOT NULL UNIQUE,
  "isActive" BOOLEAN NOT NULL DEFAULT 1,
  "createdAt" DATETIME,
  "updatedAt" DATETIME
, "uuid" TEXT);

CREATE TABLE "inventory" ( -- "002 migration"
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "price" DECIMAL(10, 2) NOT NULL,
    "quantity" INTEGER NOT NULL DEFAULT 0,
    -- "itemTypeId" INTEGER REFERENCES "item_types"("id"), -- "015 migration"
    -- "listPosition" INTEGER, -- "019 migration"
    -- "parentId" INTEGER REFERENCES "inventory"("id"), -- variant grouping: head item of the family -- "020 migration"
    -- "attributes" TEXT, -- JSON object keyed by attribute_definitions.key -- "020 migration"
    -- "excludeFromCatalog" BOOLEAN NOT NULL DEFAULT 0, -- "022 migration"
    "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
, "itemTypeId" INTEGER REFERENCES "item_types"("id"), "listPosition" INTEGER, "parentId" INTEGER REFERENCES "inventory"("id"), "attributes" TEXT, "excludeFromCatalog" BOOLEAN NOT NULL DEFAULT 0, "title" TEXT, "uuid" TEXT);

CREATE TABLE "inventory_opening_stock" ( -- "014 migration"
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "inventoryId" INTEGER NOT NULL UNIQUE,
    "quantity" INTEGER NOT NULL,
    "asOfDate" DATETIME,
    "old_quantity" INTEGER,
    "createdAt" DATETIME,
    "updatedAt" DATETIME, "uuid" TEXT,
    FOREIGN KEY ("inventoryId") REFERENCES "inventory"("id")
);

CREATE TABLE "inventory_prices" ( -- "020 migration"
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "inventoryId" INTEGER NOT NULL,
    "priceListId" INTEGER NOT NULL,
    "price" REAL NOT NULL DEFAULT 0,
    "createdAt" DATETIME,
    "updatedAt" DATETIME, "uuid" TEXT,
    UNIQUE("inventoryId", "priceListId"),
    FOREIGN KEY ("inventoryId") REFERENCES "inventory"("id") ON DELETE CASCADE,
    FOREIGN KEY ("priceListId") REFERENCES "price_lists"("id") ON DELETE CASCADE
);

CREATE TABLE "invoice_items" ( -- "002 migration"
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "invoiceId" INTEGER NOT NULL,
    "inventoryId" INTEGER NOT NULL,
    "quantity" INTEGER NOT NULL,
    -- "discount" DECIMAL(10, 2) NOT NULL DEFAULT 0, -- "004 migration"
    -- "accountId" INTEGER DEFAULT NULL, -- "010 migration"
    "price" DECIMAL(10, 2) NOT NULL,
    "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP, discount DECIMAL(10, 2) NOT NULL DEFAULT 0, "accountId" INTEGER DEFAULT NULL REFERENCES "account"("id"), "uuid" TEXT,

    FOREIGN KEY ("inventoryId") REFERENCES "inventory"("id"),
    FOREIGN KEY ("invoiceId") REFERENCES "invoices"("id")
    --, FOREIGN KEY ("accountId") REFERENCES "account"("id") -- "010 migration"
);

CREATE TABLE "invoices" ( -- "002 migration"
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "invoiceNumber" INTEGER NOT NULL,
    "accountId" INTEGER NOT NULL,
    "invoiceType" TEXT NOT NULL CHECK ("invoiceType" IN ('Purchase', 'Sale')),
    "date" DATETIME NOT NULL,
    "totalAmount" DECIMAL(10, 2) NOT NULL,
    "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP, extraDiscount DECIMAL(10, 4) NOT NULL DEFAULT 0, "biltyNumber" INTEGER, "cartons" INTEGER, "extraDiscountAccountId" INTEGER REFERENCES "account"("id"), "isReturned" BOOLEAN NOT NULL DEFAULT 0, "returnedAt" DATETIME, "returnReason" TEXT, "isQuotation" BOOLEAN NOT NULL DEFAULT 0, "uuid" TEXT,
    -- "extraDiscount" DECIMAL(10, 4) NOT NULL DEFAULT 0, -- "005 migration"
    -- "biltyNumber" INTEGER, -- "009 migration"
    -- "cartons" INTEGER, -- "009 migration"
    -- "extraDiscountAccountId" INTEGER REFERENCES "account"("id"), -- "016 migration"
    -- "isReturned" BOOLEAN NOT NULL DEFAULT 0, -- "017 migration"
    -- "returnedAt" DATETIME, -- "017 migration"
    -- "returnReason" TEXT, -- "017 migration"
    -- "isQuotation" BOOLEAN NOT NULL DEFAULT 0, -- "018 migration"

    UNIQUE("invoiceNumber", "invoiceType"),
    FOREIGN KEY ("accountId") REFERENCES "account"("id")
);

CREATE TABLE "item_types" ( -- "015 migration"
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT NOT NULL UNIQUE,
  "isActive" BOOLEAN NOT NULL DEFAULT 1,
  "isPrimary" BOOLEAN NOT NULL DEFAULT 0,
  "createdAt" DATETIME,
  "updatedAt" DATETIME
, "uuid" TEXT);

CREATE TABLE "journal" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "date" DATETIME NOT NULL,
  "narration" STRING NOT NULL,
  "isPosted" BOOLEAN NOT NULL DEFAULT 0,
  -- "billNumber" INTEGER, -- "013 migration"
  -- "discountPercentage" DECIMAL(5, 2), -- "013 migration"
  -- "invoiceId" INTEGER REFERENCES "invoices"("id"), -- "016 migration" nullable for manual journals
  "createdAt"	DATETIME,
  "updatedAt"	DATETIME
, "billNumber" INTEGER, "discountPercentage" DECIMAL(5, 2), "invoiceId" INTEGER REFERENCES "invoices"("id"), "uuid" TEXT);

CREATE TABLE "journal_entry" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "journalId" INTEGER NOT NULL,
  "debitAmount" DECIMAL DEFAULT 0,
  "creditAmount" DECIMAL DEFAULT 0,
  "accountId" INTEGER NOT NULL,
  "createdAt"	DATETIME,
  "updatedAt"	DATETIME, "uuid" TEXT,

  FOREIGN KEY("journalId") REFERENCES "journal"("id"),
  FOREIGN KEY("accountId") REFERENCES "account"("id")
);

CREATE TABLE "ledger" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "date" DATETIME NOT NULL,
  "particulars" STRING NOT NULL,
  "accountId" INTEGER,
  "debit" DECIMAL DEFAULT 0,
  "credit" DECIMAL DEFAULT 0,
  "balance" DECIMAL NOT NULL DEFAULT 0,
  "balanceType" STRING NOT NULL,
  "linkedAccountId" INTEGER,
  "createdAt"	DATETIME,
  "updatedAt"	DATETIME, "uuid" TEXT,

  FOREIGN KEY("accountId") REFERENCES "account"("id"),
  CHECK ("balanceType" IN ('Cr', 'Dr'))
);

CREATE TABLE migrations (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      name TEXT NOT NULL UNIQUE,
      applied_at DATETIME DEFAULT (DATETIME(CURRENT_TIMESTAMP, 'localtime'))
    );

CREATE TABLE "price_lists" ( -- "020 migration"
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "name" TEXT NOT NULL UNIQUE,
    "isActive" BOOLEAN NOT NULL DEFAULT 1,
    "createdAt" DATETIME,
    "updatedAt" DATETIME
, "uuid" TEXT);

CREATE TABLE "profile_type_discounts" ( -- "015 migration"
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "profileId" INTEGER NOT NULL,
  "itemTypeId" INTEGER NOT NULL,
  "discountPercent" DECIMAL(5, 2) NOT NULL DEFAULT 0 CHECK ("discountPercent" >= 0 AND "discountPercent" <= 100),
  "createdAt" DATETIME,
  "updatedAt" DATETIME, "uuid" TEXT,
  UNIQUE("profileId", "itemTypeId"),
  FOREIGN KEY ("profileId") REFERENCES "discount_profiles"("id") ON DELETE CASCADE,
  FOREIGN KEY ("itemTypeId") REFERENCES "item_types"("id") ON DELETE CASCADE
);

CREATE TABLE "stock_adjustments" ( -- "014 migration"
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "inventoryId" INTEGER NOT NULL,
    "quantityDelta" INTEGER NOT NULL,
    "reason" TEXT,
    "date" DATETIME NOT NULL,
    "createdAt" DATETIME,
    "updatedAt" DATETIME, "uuid" TEXT,
    FOREIGN KEY ("inventoryId") REFERENCES "inventory"("id")
);

CREATE TABLE "users" (
	"id" INTEGER PRIMARY KEY AUTOINCREMENT, -- https://github.com/WiseLibs/better-sqlite3/blob/master/docs/tips.md#creating-good-tables
	"username" TEXT UNIQUE,
	"password_hash"	BLOB,
	"status" INTEGER DEFAULT 0,
  "createdAt"	DATETIME,
  "updatedAt"	DATETIME
);

CREATE INDEX idx_account_discountProfileId
            ON account(discountProfileId);

CREATE UNIQUE INDEX "idx_account_uuid" ON "account"("uuid");

CREATE UNIQUE INDEX "idx_attribute_definitions_uuid" ON "attribute_definitions"("uuid");

CREATE UNIQUE INDEX "idx_chart_uuid" ON "chart"("uuid");

CREATE UNIQUE INDEX "idx_discount_profiles_uuid" ON "discount_profiles"("uuid");

CREATE INDEX idx_inventory_itemTypeId
            ON inventory(itemTypeId);

CREATE UNIQUE INDEX "idx_inventory_opening_stock_uuid" ON "inventory_opening_stock"("uuid");

CREATE INDEX idx_inventory_parentId ON inventory(parentId);

CREATE INDEX idx_inventory_prices_inventoryId ON inventory_prices(inventoryId);

CREATE INDEX idx_inventory_prices_priceListId ON inventory_prices(priceListId);

CREATE UNIQUE INDEX "idx_inventory_prices_uuid" ON "inventory_prices"("uuid");

CREATE UNIQUE INDEX "idx_inventory_uuid" ON "inventory"("uuid");

CREATE INDEX idx_invoice_items_inventoryId ON invoice_items(inventoryId);

CREATE INDEX idx_invoice_items_invoiceId ON invoice_items(invoiceId);

CREATE UNIQUE INDEX "idx_invoice_items_uuid" ON "invoice_items"("uuid");

CREATE UNIQUE INDEX "idx_invoices_uuid" ON "invoices"("uuid");

CREATE UNIQUE INDEX "idx_item_types_uuid" ON "item_types"("uuid");

CREATE INDEX idx_journal_entry_accountId ON journal_entry(accountId);

CREATE INDEX idx_journal_entry_journalId ON journal_entry(journalId);

CREATE UNIQUE INDEX "idx_journal_entry_uuid" ON "journal_entry"("uuid");

CREATE INDEX idx_journal_invoiceId ON journal(invoiceId);

CREATE UNIQUE INDEX "idx_journal_uuid" ON "journal"("uuid");

CREATE INDEX idx_ledger_accountId_date ON ledger(accountId, date, id);

CREATE UNIQUE INDEX "idx_ledger_uuid" ON "ledger"("uuid");

CREATE UNIQUE INDEX "idx_price_lists_uuid" ON "price_lists"("uuid");

CREATE INDEX idx_profile_type_discounts_itemTypeId
            ON profile_type_discounts(itemTypeId);

CREATE INDEX idx_profile_type_discounts_profileId
            ON profile_type_discounts(profileId);

CREATE UNIQUE INDEX "idx_profile_type_discounts_uuid" ON "profile_type_discounts"("uuid");

CREATE INDEX idx_stock_adjustments_inventoryId ON stock_adjustments(inventoryId);

CREATE UNIQUE INDEX "idx_stock_adjustments_uuid" ON "stock_adjustments"("uuid");

CREATE UNIQUE INDEX "unique_account_name_and_code_in_chart" ON "account" ("chartId", "name", "code");

CREATE TRIGGER after_insert_account_add_timestamp
              AFTER INSERT ON account
              BEGIN
                UPDATE account SET
                  createdAt = datetime(CURRENT_TIMESTAMP, 'localtime'),
                  updatedAt = datetime(CURRENT_TIMESTAMP, 'localtime')
                WHERE id = NEW.id;
              END;

CREATE TRIGGER after_insert_attribute_definitions_add_timestamp
AFTER INSERT ON attribute_definitions
BEGIN
  UPDATE attribute_definitions SET
    createdAt = datetime(CURRENT_TIMESTAMP, 'localtime'),
    updatedAt = datetime(CURRENT_TIMESTAMP, 'localtime')
  WHERE id = NEW.id;
END;

CREATE TRIGGER after_insert_chart_add_timestamp
              AFTER INSERT ON chart
              BEGIN
                UPDATE chart SET
                  createdAt = datetime(CURRENT_TIMESTAMP, 'localtime'),
                  updatedAt = datetime(CURRENT_TIMESTAMP, 'localtime')
                WHERE id = NEW.id;
              END;

CREATE TRIGGER after_insert_discount_profiles_add_timestamp
AFTER INSERT ON discount_profiles
BEGIN
  UPDATE discount_profiles SET
    createdAt = datetime(CURRENT_TIMESTAMP, 'localtime'),
    updatedAt = datetime(CURRENT_TIMESTAMP, 'localtime')
  WHERE id = NEW.id;
END;

CREATE TRIGGER after_insert_inventory_add_timestamp
AFTER INSERT ON inventory
BEGIN
  UPDATE inventory SET
    createdAt = datetime(CURRENT_TIMESTAMP, 'localtime'),
    updatedAt = datetime(CURRENT_TIMESTAMP, 'localtime')
  WHERE id = NEW.id;
END;

CREATE TRIGGER after_insert_inventory_opening_stock_add_timestamp
AFTER INSERT ON inventory_opening_stock
BEGIN
  UPDATE inventory_opening_stock SET
    createdAt = datetime(CURRENT_TIMESTAMP, 'localtime'),
    updatedAt = datetime(CURRENT_TIMESTAMP, 'localtime')
  WHERE id = NEW.id;
END;

CREATE TRIGGER after_insert_inventory_prices_add_timestamp
AFTER INSERT ON inventory_prices
BEGIN
  UPDATE inventory_prices SET
    createdAt = datetime(CURRENT_TIMESTAMP, 'localtime'),
    updatedAt = datetime(CURRENT_TIMESTAMP, 'localtime')
  WHERE id = NEW.id;
END;

CREATE TRIGGER after_insert_invoice_items_add_timestamp
AFTER INSERT ON invoice_items
BEGIN
  UPDATE invoice_items SET
    createdAt = datetime(CURRENT_TIMESTAMP, 'localtime'),
    updatedAt = datetime(CURRENT_TIMESTAMP, 'localtime')
  WHERE id = NEW.id;
END;

CREATE TRIGGER after_insert_invoices_add_timestamp
AFTER INSERT ON invoices
BEGIN
  UPDATE invoices SET
    createdAt = datetime(CURRENT_TIMESTAMP, 'localtime'),
    updatedAt = datetime(CURRENT_TIMESTAMP, 'localtime')
  WHERE id = NEW.id;
END;

CREATE TRIGGER after_insert_item_types_add_timestamp
AFTER INSERT ON item_types
BEGIN
  UPDATE item_types SET
    createdAt = datetime(CURRENT_TIMESTAMP, 'localtime'),
    updatedAt = datetime(CURRENT_TIMESTAMP, 'localtime')
  WHERE id = NEW.id;
END;

CREATE TRIGGER after_insert_journal_add_timestamp
AFTER INSERT ON journal
BEGIN
  UPDATE journal SET
    createdAt = datetime(CURRENT_TIMESTAMP, 'localtime'),
    updatedAt = datetime(CURRENT_TIMESTAMP, 'localtime')
  WHERE id = NEW.id;
END;

CREATE TRIGGER after_insert_journal_entry_add_timestamp
AFTER INSERT ON journal_entry
BEGIN
  UPDATE journal_entry SET
    createdAt = datetime(CURRENT_TIMESTAMP, 'localtime'),
    updatedAt = datetime(CURRENT_TIMESTAMP, 'localtime')
  WHERE id = NEW.id;
END;

CREATE TRIGGER after_insert_ledger_add_timestamp
AFTER INSERT ON ledger
BEGIN
  UPDATE ledger SET
    createdAt = datetime(CURRENT_TIMESTAMP, 'localtime'),
    updatedAt = datetime(CURRENT_TIMESTAMP, 'localtime')
  WHERE id = NEW.id;
END;

CREATE TRIGGER after_insert_price_lists_add_timestamp
AFTER INSERT ON price_lists
BEGIN
  UPDATE price_lists SET
    createdAt = datetime(CURRENT_TIMESTAMP, 'localtime'),
    updatedAt = datetime(CURRENT_TIMESTAMP, 'localtime')
  WHERE id = NEW.id;
END;

CREATE TRIGGER after_insert_profile_type_discounts_add_timestamp
AFTER INSERT ON profile_type_discounts
BEGIN
  UPDATE profile_type_discounts SET
    createdAt = datetime(CURRENT_TIMESTAMP, 'localtime'),
    updatedAt = datetime(CURRENT_TIMESTAMP, 'localtime')
  WHERE id = NEW.id;
END;

CREATE TRIGGER after_insert_stock_adjustments_add_timestamp
AFTER INSERT ON stock_adjustments
BEGIN
  UPDATE stock_adjustments SET
    createdAt = datetime(CURRENT_TIMESTAMP, 'localtime'),
    updatedAt = datetime(CURRENT_TIMESTAMP, 'localtime')
  WHERE id = NEW.id;
END;

CREATE TRIGGER after_insert_users_add_timestamp
AFTER INSERT ON users
BEGIN
  UPDATE users SET
    createdAt = datetime(CURRENT_TIMESTAMP, 'localtime'),
    updatedAt = datetime(CURRENT_TIMESTAMP, 'localtime')
  WHERE id = NEW.id;
END;

CREATE TRIGGER after_update_account_add_timestamp
              AFTER UPDATE ON account
              BEGIN
                UPDATE account SET
                  updatedAt = datetime(CURRENT_TIMESTAMP, 'localtime')
                WHERE id = NEW.id;
              END;

CREATE TRIGGER after_update_attribute_definitions_add_timestamp
AFTER UPDATE ON attribute_definitions
BEGIN
  UPDATE attribute_definitions SET
    updatedAt = datetime(CURRENT_TIMESTAMP, 'localtime')
  WHERE id = NEW.id;
END;

CREATE TRIGGER after_update_chart_add_timestamp
              AFTER UPDATE ON chart
              BEGIN
                UPDATE chart SET
                  updatedAt = datetime(CURRENT_TIMESTAMP, 'localtime')
                WHERE id = NEW.id;
              END;

CREATE TRIGGER after_update_discount_profiles_add_timestamp
AFTER UPDATE ON discount_profiles
BEGIN
  UPDATE discount_profiles SET
    updatedAt = datetime(CURRENT_TIMESTAMP, 'localtime')
  WHERE id = NEW.id;
END;

CREATE TRIGGER after_update_inventory_add_timestamp
AFTER UPDATE ON inventory
BEGIN
  UPDATE inventory SET
    updatedAt = datetime(CURRENT_TIMESTAMP, 'localtime')
  WHERE id = NEW.id;
END;

CREATE TRIGGER after_update_inventory_opening_stock_add_timestamp
AFTER UPDATE ON inventory_opening_stock
BEGIN
  UPDATE inventory_opening_stock SET
    updatedAt = datetime(CURRENT_TIMESTAMP, 'localtime')
  WHERE id = NEW.id;
END;

CREATE TRIGGER after_update_inventory_prices_add_timestamp
AFTER UPDATE ON inventory_prices
BEGIN
  UPDATE inventory_prices SET
    updatedAt = datetime(CURRENT_TIMESTAMP, 'localtime')
  WHERE id = NEW.id;
END;

CREATE TRIGGER after_update_invoice_items_add_timestamp
AFTER UPDATE ON invoice_items
BEGIN
  UPDATE invoice_items SET
    updatedAt = datetime(CURRENT_TIMESTAMP, 'localtime')
  WHERE id = NEW.id;
END;

CREATE TRIGGER after_update_invoices_add_timestamp
AFTER UPDATE ON invoices
BEGIN
  UPDATE invoices SET
    updatedAt = datetime(CURRENT_TIMESTAMP, 'localtime')
  WHERE id = NEW.id;
END;

CREATE TRIGGER after_update_item_types_add_timestamp
AFTER UPDATE ON item_types
BEGIN
  UPDATE item_types SET
    updatedAt = datetime(CURRENT_TIMESTAMP, 'localtime')
  WHERE id = NEW.id;
END;

CREATE TRIGGER after_update_journal_add_timestamp
AFTER UPDATE ON journal
BEGIN
  UPDATE journal SET
    updatedAt = datetime(CURRENT_TIMESTAMP, 'localtime')
  WHERE id = NEW.id;
END;

CREATE TRIGGER after_update_journal_entry_add_timestamp
AFTER UPDATE ON journal_entry
BEGIN
  UPDATE journal_entry SET
    updatedAt = datetime(CURRENT_TIMESTAMP, 'localtime')
  WHERE id = NEW.id;
END;

CREATE TRIGGER after_update_ledger_add_timestamp
AFTER UPDATE ON ledger
BEGIN
  UPDATE ledger SET
    updatedAt = datetime(CURRENT_TIMESTAMP, 'localtime')
  WHERE id = NEW.id;
END;

CREATE TRIGGER after_update_price_lists_add_timestamp
AFTER UPDATE ON price_lists
BEGIN
  UPDATE price_lists SET
    updatedAt = datetime(CURRENT_TIMESTAMP, 'localtime')
  WHERE id = NEW.id;
END;

CREATE TRIGGER after_update_profile_type_discounts_add_timestamp
AFTER UPDATE ON profile_type_discounts
BEGIN
  UPDATE profile_type_discounts SET
    updatedAt = datetime(CURRENT_TIMESTAMP, 'localtime')
  WHERE id = NEW.id;
END;

CREATE TRIGGER after_update_stock_adjustments_add_timestamp
AFTER UPDATE ON stock_adjustments
BEGIN
  UPDATE stock_adjustments SET
    updatedAt = datetime(CURRENT_TIMESTAMP, 'localtime')
  WHERE id = NEW.id;
END;

CREATE TRIGGER after_update_users_add_timestamp
AFTER UPDATE ON users
BEGIN
  UPDATE users SET
    updatedAt = datetime(CURRENT_TIMESTAMP, 'localtime')
  WHERE id = NEW.id;
END;

CREATE TRIGGER "trg_account_uuid"
              AFTER INSERT ON "account"
              WHEN NEW."uuid" IS NULL
              BEGIN
                UPDATE "account" SET "uuid" = (
                  SELECT lower(
                    hex(randomblob(4)) || '-' ||
                    hex(randomblob(2)) || '-4' ||
                    substr(hex(randomblob(2)), 2) || '-' ||
                    substr('89ab', abs(random()) % 4 + 1, 1) ||
                    substr(hex(randomblob(2)), 2) || '-' ||
                    hex(randomblob(6))
                  )
                )
                WHERE "id" = NEW."id";
              END;

CREATE TRIGGER "trg_attribute_definitions_uuid"
              AFTER INSERT ON "attribute_definitions"
              WHEN NEW."uuid" IS NULL
              BEGIN
                UPDATE "attribute_definitions" SET "uuid" = (
                  SELECT lower(
                    hex(randomblob(4)) || '-' ||
                    hex(randomblob(2)) || '-4' ||
                    substr(hex(randomblob(2)), 2) || '-' ||
                    substr('89ab', abs(random()) % 4 + 1, 1) ||
                    substr(hex(randomblob(2)), 2) || '-' ||
                    hex(randomblob(6))
                  )
                )
                WHERE "id" = NEW."id";
              END;

CREATE TRIGGER "trg_chart_uuid"
              AFTER INSERT ON "chart"
              WHEN NEW."uuid" IS NULL
              BEGIN
                UPDATE "chart" SET "uuid" = (
                  SELECT lower(
                    hex(randomblob(4)) || '-' ||
                    hex(randomblob(2)) || '-4' ||
                    substr(hex(randomblob(2)), 2) || '-' ||
                    substr('89ab', abs(random()) % 4 + 1, 1) ||
                    substr(hex(randomblob(2)), 2) || '-' ||
                    hex(randomblob(6))
                  )
                )
                WHERE "id" = NEW."id";
              END;

CREATE TRIGGER "trg_discount_profiles_uuid"
              AFTER INSERT ON "discount_profiles"
              WHEN NEW."uuid" IS NULL
              BEGIN
                UPDATE "discount_profiles" SET "uuid" = (
                  SELECT lower(
                    hex(randomblob(4)) || '-' ||
                    hex(randomblob(2)) || '-4' ||
                    substr(hex(randomblob(2)), 2) || '-' ||
                    substr('89ab', abs(random()) % 4 + 1, 1) ||
                    substr(hex(randomblob(2)), 2) || '-' ||
                    hex(randomblob(6))
                  )
                )
                WHERE "id" = NEW."id";
              END;

CREATE TRIGGER "trg_inventory_opening_stock_uuid"
              AFTER INSERT ON "inventory_opening_stock"
              WHEN NEW."uuid" IS NULL
              BEGIN
                UPDATE "inventory_opening_stock" SET "uuid" = (
                  SELECT lower(
                    hex(randomblob(4)) || '-' ||
                    hex(randomblob(2)) || '-4' ||
                    substr(hex(randomblob(2)), 2) || '-' ||
                    substr('89ab', abs(random()) % 4 + 1, 1) ||
                    substr(hex(randomblob(2)), 2) || '-' ||
                    hex(randomblob(6))
                  )
                )
                WHERE "id" = NEW."id";
              END;

CREATE TRIGGER "trg_inventory_prices_uuid"
              AFTER INSERT ON "inventory_prices"
              WHEN NEW."uuid" IS NULL
              BEGIN
                UPDATE "inventory_prices" SET "uuid" = (
                  SELECT lower(
                    hex(randomblob(4)) || '-' ||
                    hex(randomblob(2)) || '-4' ||
                    substr(hex(randomblob(2)), 2) || '-' ||
                    substr('89ab', abs(random()) % 4 + 1, 1) ||
                    substr(hex(randomblob(2)), 2) || '-' ||
                    hex(randomblob(6))
                  )
                )
                WHERE "id" = NEW."id";
              END;

CREATE TRIGGER "trg_inventory_uuid"
              AFTER INSERT ON "inventory"
              WHEN NEW."uuid" IS NULL
              BEGIN
                UPDATE "inventory" SET "uuid" = (
                  SELECT lower(
                    hex(randomblob(4)) || '-' ||
                    hex(randomblob(2)) || '-4' ||
                    substr(hex(randomblob(2)), 2) || '-' ||
                    substr('89ab', abs(random()) % 4 + 1, 1) ||
                    substr(hex(randomblob(2)), 2) || '-' ||
                    hex(randomblob(6))
                  )
                )
                WHERE "id" = NEW."id";
              END;

CREATE TRIGGER "trg_invoice_items_uuid"
              AFTER INSERT ON "invoice_items"
              WHEN NEW."uuid" IS NULL
              BEGIN
                UPDATE "invoice_items" SET "uuid" = (
                  SELECT lower(
                    hex(randomblob(4)) || '-' ||
                    hex(randomblob(2)) || '-4' ||
                    substr(hex(randomblob(2)), 2) || '-' ||
                    substr('89ab', abs(random()) % 4 + 1, 1) ||
                    substr(hex(randomblob(2)), 2) || '-' ||
                    hex(randomblob(6))
                  )
                )
                WHERE "id" = NEW."id";
              END;

CREATE TRIGGER "trg_invoices_uuid"
              AFTER INSERT ON "invoices"
              WHEN NEW."uuid" IS NULL
              BEGIN
                UPDATE "invoices" SET "uuid" = (
                  SELECT lower(
                    hex(randomblob(4)) || '-' ||
                    hex(randomblob(2)) || '-4' ||
                    substr(hex(randomblob(2)), 2) || '-' ||
                    substr('89ab', abs(random()) % 4 + 1, 1) ||
                    substr(hex(randomblob(2)), 2) || '-' ||
                    hex(randomblob(6))
                  )
                )
                WHERE "id" = NEW."id";
              END;

CREATE TRIGGER "trg_item_types_uuid"
              AFTER INSERT ON "item_types"
              WHEN NEW."uuid" IS NULL
              BEGIN
                UPDATE "item_types" SET "uuid" = (
                  SELECT lower(
                    hex(randomblob(4)) || '-' ||
                    hex(randomblob(2)) || '-4' ||
                    substr(hex(randomblob(2)), 2) || '-' ||
                    substr('89ab', abs(random()) % 4 + 1, 1) ||
                    substr(hex(randomblob(2)), 2) || '-' ||
                    hex(randomblob(6))
                  )
                )
                WHERE "id" = NEW."id";
              END;

CREATE TRIGGER "trg_journal_entry_uuid"
              AFTER INSERT ON "journal_entry"
              WHEN NEW."uuid" IS NULL
              BEGIN
                UPDATE "journal_entry" SET "uuid" = (
                  SELECT lower(
                    hex(randomblob(4)) || '-' ||
                    hex(randomblob(2)) || '-4' ||
                    substr(hex(randomblob(2)), 2) || '-' ||
                    substr('89ab', abs(random()) % 4 + 1, 1) ||
                    substr(hex(randomblob(2)), 2) || '-' ||
                    hex(randomblob(6))
                  )
                )
                WHERE "id" = NEW."id";
              END;

CREATE TRIGGER "trg_journal_uuid"
              AFTER INSERT ON "journal"
              WHEN NEW."uuid" IS NULL
              BEGIN
                UPDATE "journal" SET "uuid" = (
                  SELECT lower(
                    hex(randomblob(4)) || '-' ||
                    hex(randomblob(2)) || '-4' ||
                    substr(hex(randomblob(2)), 2) || '-' ||
                    substr('89ab', abs(random()) % 4 + 1, 1) ||
                    substr(hex(randomblob(2)), 2) || '-' ||
                    hex(randomblob(6))
                  )
                )
                WHERE "id" = NEW."id";
              END;

CREATE TRIGGER "trg_ledger_uuid"
              AFTER INSERT ON "ledger"
              WHEN NEW."uuid" IS NULL
              BEGIN
                UPDATE "ledger" SET "uuid" = (
                  SELECT lower(
                    hex(randomblob(4)) || '-' ||
                    hex(randomblob(2)) || '-4' ||
                    substr(hex(randomblob(2)), 2) || '-' ||
                    substr('89ab', abs(random()) % 4 + 1, 1) ||
                    substr(hex(randomblob(2)), 2) || '-' ||
                    hex(randomblob(6))
                  )
                )
                WHERE "id" = NEW."id";
              END;

CREATE TRIGGER "trg_price_lists_uuid"
              AFTER INSERT ON "price_lists"
              WHEN NEW."uuid" IS NULL
              BEGIN
                UPDATE "price_lists" SET "uuid" = (
                  SELECT lower(
                    hex(randomblob(4)) || '-' ||
                    hex(randomblob(2)) || '-4' ||
                    substr(hex(randomblob(2)), 2) || '-' ||
                    substr('89ab', abs(random()) % 4 + 1, 1) ||
                    substr(hex(randomblob(2)), 2) || '-' ||
                    hex(randomblob(6))
                  )
                )
                WHERE "id" = NEW."id";
              END;

CREATE TRIGGER "trg_profile_type_discounts_uuid"
              AFTER INSERT ON "profile_type_discounts"
              WHEN NEW."uuid" IS NULL
              BEGIN
                UPDATE "profile_type_discounts" SET "uuid" = (
                  SELECT lower(
                    hex(randomblob(4)) || '-' ||
                    hex(randomblob(2)) || '-4' ||
                    substr(hex(randomblob(2)), 2) || '-' ||
                    substr('89ab', abs(random()) % 4 + 1, 1) ||
                    substr(hex(randomblob(2)), 2) || '-' ||
                    hex(randomblob(6))
                  )
                )
                WHERE "id" = NEW."id";
              END;

CREATE TRIGGER "trg_stock_adjustments_uuid"
              AFTER INSERT ON "stock_adjustments"
              WHEN NEW."uuid" IS NULL
              BEGIN
                UPDATE "stock_adjustments" SET "uuid" = (
                  SELECT lower(
                    hex(randomblob(4)) || '-' ||
                    hex(randomblob(2)) || '-4' ||
                    substr(hex(randomblob(2)), 2) || '-' ||
                    substr('89ab', abs(random()) % 4 + 1, 1) ||
                    substr(hex(randomblob(2)), 2) || '-' ||
                    hex(randomblob(6))
                  )
                )
                WHERE "id" = NEW."id";
              END;

CREATE VIEW inventory_quantity_view AS
            SELECT
              i.id AS inventoryId,
              COALESCE(os.quantity, 0)
              + COALESCE((
                  SELECT SUM(
                    CASE
                      WHEN COALESCE(inv.isQuotation, 0) != 0 THEN 0
                      WHEN inv.invoiceType = 'Sale' THEN
                        CASE WHEN COALESCE(inv.isReturned, 0) = 0 THEN -ii.quantity ELSE 0 END
                      WHEN inv.invoiceType = 'Purchase' THEN
                        CASE WHEN COALESCE(inv.isReturned, 0) = 0 THEN ii.quantity ELSE 0 END
                      ELSE 0
                    END
                  )
                  FROM invoice_items ii
                  JOIN invoices inv ON inv.id = ii.invoiceId
                  WHERE ii.inventoryId = i.id
                ), 0)
              + COALESCE((
                  SELECT SUM(sa.quantityDelta)
                  FROM stock_adjustments sa
                  WHERE sa.inventoryId = i.id
                ), 0) AS quantity
            FROM inventory i
            LEFT JOIN inventory_opening_stock os ON os.inventoryId = i.id;

CREATE VIEW journal_entry_pairs AS
            SELECT
              j.id AS journalId,
              j.date AS date,
              j.narration AS narration,
              d.id AS debitEntryId,
              d.accountId AS debitAccountId,
              d.debitAmount AS debitAmount,
              c.id AS creditEntryId,
              c.accountId AS creditAccountId,
              c.creditAmount AS creditAmount,
              (SELECT SUM(je.debitAmount) FROM journal_entry je WHERE je.journalId = j.id) AS totalDebits,
              (SELECT SUM(je.creditAmount) FROM journal_entry je WHERE je.journalId = j.id) AS totalCredits
            FROM journal j
            JOIN journal_entry d ON d.journalId = j.id AND d.debitAmount > 0
            JOIN journal_entry c ON c.journalId = j.id AND c.creditAmount > 0;

CREATE VIEW ledger_lines AS
            SELECT
              debitAccountId AS accountId,
              date,
              creditAccountId AS linkedAccountId,
              (debitAmount * creditAmount) / totalCredits AS debit,
              0 AS credit,
              CASE WHEN narration = 'Opening Balance from B/S' THEN narration
                   ELSE 'Journal #' || journalId END AS particulars,
              journalId,
              debitEntryId AS ownEntryId,
              creditEntryId AS counterEntryId
            FROM journal_entry_pairs
            UNION ALL
            SELECT
              creditAccountId AS accountId,
              date,
              debitAccountId AS linkedAccountId,
              0 AS debit,
              (creditAmount * debitAmount) / totalDebits AS credit,
              CASE WHEN narration = 'Opening Balance from B/S' THEN narration
                   ELSE 'Journal #' || journalId END AS particulars,
              journalId,
              creditEntryId AS ownEntryId,
              debitEntryId AS counterEntryId
            FROM journal_entry_pairs;

CREATE VIEW ledger_view AS
            SELECT
              ll.accountId,
              ll.date,
              ll.particulars,
              ll.debit,
              ll.credit,
              ll.linkedAccountId,
              ll.journalId,
              ll.ownEntryId,
              ll.counterEntryId,
              ABS(SUM(
                CASE WHEN ct.type IN ('Asset', 'Expense') THEN ll.debit - ll.credit
                     ELSE ll.credit - ll.debit END
              ) OVER (
                PARTITION BY ll.accountId
                ORDER BY datetime(ll.date, 'localtime'), ll.ownEntryId, ll.counterEntryId
                ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
              )) AS balance,
              CASE WHEN (
                SUM(
                  CASE WHEN ct.type IN ('Asset', 'Expense') THEN ll.debit - ll.credit
                       ELSE ll.credit - ll.debit END
                ) OVER (
                  PARTITION BY ll.accountId
                  ORDER BY datetime(ll.date, 'localtime'), ll.ownEntryId, ll.counterEntryId
                  ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
                )
              ) >= 0
                THEN CASE WHEN ct.type IN ('Asset', 'Expense') THEN 'Dr' ELSE 'Cr' END
                ELSE CASE WHEN ct.type IN ('Asset', 'Expense') THEN 'Cr' ELSE 'Dr' END
              END AS balanceType
            FROM ledger_lines ll
            JOIN account a ON a.id = ll.accountId
            JOIN chart ct ON ct.id = a.chartId;

-- Mark migrations 001-027 as already applied.
INSERT INTO migrations (name) VALUES ('001_update_chart_type_constraint');
INSERT INTO migrations (name) VALUES ('002_add_inventory_and_invoice_modules');
INSERT INTO migrations (name) VALUES ('003_add_invoice_items_triggers');
INSERT INTO migrations (name) VALUES ('004_add_discount_in_invoice_items_table');
INSERT INTO migrations (name) VALUES ('005_add_extra_discount_in_invoice_table');
INSERT INTO migrations (name) VALUES ('006_add_parentId_in_chart_table');
INSERT INTO migrations (name) VALUES ('007_add_address_phone1_phone2_goodsName_in_account_table');
INSERT INTO migrations (name) VALUES ('008_update_account_code_type');
INSERT INTO migrations (name) VALUES ('009_add_biltyNumber_cartons_in_invoices_table');
INSERT INTO migrations (name) VALUES ('010_add_account_id_to_invoice_items_table');
INSERT INTO migrations (name) VALUES ('011_add_unique_constraint_to_account_name_and_code_in_chart');
INSERT INTO migrations (name) VALUES ('012_add_isActive_to_account_table');
INSERT INTO migrations (name) VALUES ('013_add_billNumber_and_discountPercentage_to_journal_table');
INSERT INTO migrations (name) VALUES ('014_opening_stock_and_stock_adjustments');
INSERT INTO migrations (name) VALUES ('015_add_item_types_and_discount_profiles');
INSERT INTO migrations (name) VALUES ('016_add_journal_invoiceId_and_invoice_extraDiscountAccountId');
INSERT INTO migrations (name) VALUES ('017_add_invoice_return_fields');
INSERT INTO migrations (name) VALUES ('018_add_invoices_isQuotation');
INSERT INTO migrations (name) VALUES ('019_add_inventory_listPosition');
INSERT INTO migrations (name) VALUES ('020_add_attributes_families_and_price_lists');
INSERT INTO migrations (name) VALUES ('021_add_attribute_isPublic');
INSERT INTO migrations (name) VALUES ('022_add_inventory_excludeFromCatalog');
INSERT INTO migrations (name) VALUES ('023_add_inventory_title');
INSERT INTO migrations (name) VALUES ('024_add_uuid_to_business_tables');
INSERT INTO migrations (name) VALUES ('025_migrate_opening_balance_ledger_to_journal');
INSERT INTO migrations (name) VALUES ('026_index_journal_entry_and_ledger_lookup');
INSERT INTO migrations (name) VALUES ('027_create_ledger_and_inventory_quantity_views');
