/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false workers/env.d.ts` (hash: d5b8b1e1205912e2334bbe4e07906abd)
interface __BaseEnv_Env {
  FONTS: R2Bucket;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./urduPrintFont');
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
